apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  labels:
    app.kubernetes.io/name: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
