apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend

images:
  - name: frontend
    # Replace mohamed710 with your Docker Hub namespace
    # (the same value as the mohamed710 repo variable).
    newName: docker.io/mohamed710/frontend
    newTag: e760ef6651cacb3118e61c06247f041a0f94cc21
