apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/frontend

images:
  - name: frontend
    # Replace mohamed710 with your Docker Hub namespace
    # (the same value as the mohamed710 repo variable).
    newName: docker.io/mohamed710/frontend
    newTag: b920933a93dd35bcf8b2d2c304b3a316a94e82e2
