apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backend

images:
  - name: backend
    # Replace mohamed710 with your Docker Hub namespace
    # (the same value as the mohamed710 repo variable).
    newName: docker.io/mohamed710/backend
    newTag: 6c5ceeacb12236211b095bf035277efc5721814e
