apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backend

images:
  - name: backend
    # Replace mohamed710 with your Docker Hub namespace
    # (the same value as the mohamed710 repo variable).
    newName: docker.io/mohamed710/backend
    digest: sha256:99b8da5186d3077ca0ed199bc519d26e491f6977551b223d6cf8ec9c585a1f2e
